apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: users
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort | default nil }}
      protocol: TCP
  type: {{ .Values.service.type }}
