apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: dnkq/users:latest
          ports:
            - containerPort: 8000
